### ISSUE TITLE
请教怎么从NIMOJS/blog跳转到onface/blog

### ISSUE THREAD

**Issue by LiYun9** [onface/blog#29]
请教怎么从NIMOJS/blog跳转到onface/blog？

谢谢

**Comment by nimojs** [comment]
@LiYun9  github 自带的，当你移交项目时，链接我自行跳转。
比如 nimojs/blog 转换为 onface/blog  那么 链接会自行跳转，但是 如果你重新新建了 nimojs/blog 就没用。

还有 nimojs.github.io/blog 的代码无法跳转到 onface/blog
